name: Publish WRIMS GUI installer

on:
  release:
    types: [ published ]

jobs:
  build:
    permissions: write-all
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        env:
          PKG_USERNAME: ${{ github.actor }}
          PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew clean
          ./gradlew build
          ./gradlew :wrims-gui:zipWrimsGui
          ./gradlew :wrims-gui:zipWrimsPatch

      - name: Attach WRIMS Installer zip to github deployment
        run: |
          gh release upload ${{ github.event.release.tag_name }} wrims-gui/build/installer/wrims_gui_x64_${{ github.event.release.tag_name }}.zip --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach WRIMS Patch zip to github deployment
        run: |
          gh release upload ${{ github.event.release.tag_name }} wrims-gui/build/patch/wrims_patch_v2.2.0_basis.zip --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach WRIMS Patch release date to github deployment
        run: |
          gh release upload ${{ github.event.release.tag_name }} wrims-gui/build/patch/releasedate_v2.2.0_basis.log --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}